services:
  vm:
    container_name: vm
    build: ./docker/vm

  api:
    container_name: api
    build: .
    environment:
      - PORT=8001
    ports:
      - 8001:8001
    volumes:
      - ./api:/app/api
      - db-data:/var/storages/sendit-ide
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp:/tmp
    extra_hosts:
      - "host.docker.internal:host-gateway"
    develop:
      watch:
        - action: rebuild
          path: Dockerfile
        - action: rebuild
          path: package.json
    command: npm run dev

volumes:
  db-data: